// dev
@host = localhost
// @host = 192.168.1.152
@port = 8470
@baseUri = https://{{host}}:{{port}}
@uri = {{baseUri}}/api
@contentType = application/json
@apiKey = 5KmgFcy1X7bbcbtSuOtXEZXYslKyB0n3g3xRmCaaNsAwB9dhOpKuhZ04Mfr2OKGL

### ping
// @name ping

GET {{baseUri}}/ping HTTP/1.1
Content-Type: {{contentType}}

### postFilter
// @name postFilter

POST {{uri}}/state HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

{ 
  // defaults
  // "filterFile": "^.*c3-.*\\.log$",
  // "filterLine": "(?i)(.*)"
  // custom
  // "filterFile": "^.*c3-microcloud-backend.log", 
  // "filterLine": "(?i)(httpModule)"
  // fire error in regEx
  "filterFile": "^\\/var\\/log\/samba\/samba.log$",
  "filterLine": "(?i)(httpModule)"
}

### getState
// @name getState

GET {{uri}}/state HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

{ 
}

### getConfig
// @name getConfig

GET {{uri}}/config HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

{ 
}

### buildBackupLog
// @name buildLogBackup

POST {{uri}}/backup-log HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
  // "key": "all"
  // "key" : "squid-all"
  "key" : "squid-cache"
  // "key" : "c3-microcloud-backend"
}

### test endpoints currently disabled

### greet
// @name greet

GET {{uri}}/ HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

### greetJohn
// @name greetJohn

GET {{uri}}/John HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

### wsEcho
// @name wsEcho

POST {{uri}}/ws-echo HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{apiKey}}

{
  "message": "hi there"
}